[plotting]
cmap = "tab20c"

[io]
separator = "\t"
drop_cols = ["^column_.*$", "^ExtCal.*$"]
drop_rows = "^.*rat.*|.*nitric.*$|^.*DNU.*$"

[groups]
"15mL water flush" = ["A1", "B1", "C1", "D1", "E1"]
"15mL glycerol flush" = ["A2", "B2", "C2", "D2", "E2"]
"Tubing in acid" = ["A3", "B3", "C3", "D3", "E3"]
"Sonication" = ["A4", "B4", "C4", "D4", "E4"]
"4mL water flush" = ["A5", "B5", "C5", "D5", "E5"]
"2mL water flush" = ["A6", "B6", "C6", "D6", "E6"]
"Riffled" = ["Riffled vial 2712"]
"Glycerin control" = ["Glycering control"]

[dilutions]
"A1" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"B1" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"C1" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"D1" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"E1" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"A2" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"B2" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"C2" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"D2" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"E2" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"A3" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"B3" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"C3" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"D3" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"E3" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"A4" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"B4" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"C4" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"D4" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"E4" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"A5" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"B5" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"C5" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"D5" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"E5" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"A6" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"B6" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"C6" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"D6" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"E6" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
"Riffled" = { V_initial = 4.0, V_digestion = 22.65, V_aliquot = 1.000, V_final = 10 }
"Glycerin control" = { V_initial = 18.88, V_digestion = 37.76, V_aliquot = 8.235, V_final = 10 }
