[plotting]
cmap = "tab20c"

[io]
separator = "\t"
drop_cols = ["^column_.*$", "^ExtCal.*$"]
drop_rows = "^.*rat.*|.*nitric.*$|^.*DNU.*$"

[groups]
"0.4" = ["0.4"]
"0.2" = ["0.2"]
"0.15" = ["0.15"]
"0.1" = ["0.1"]
"0.05" = ["0.05"]

[dilutions]
"0.4" = { V_initial = 0.75, V_digestion = 15, V_aliquot = 8.235, V_final = 10 }
"0.2" = { V_initial = 3, V_digestion = 15, V_aliquot = 8.235, V_final = 10 }
"0.15" = { V_initial = 2.25, V_digestion = 15, V_aliquot = 8.235, V_final = 10 }
"0.1" = { V_initial = 1.5, V_digestion = 15, V_aliquot = 8.235, V_final = 10 }
"0.05" = { V_initial = 0.75, V_digestion = 15, V_aliquot = 8.235, V_final = 10 }
